# docker-compose.yml
version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "8080:80"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=student_db
      - DB_PORT=3306
    depends_on:
      - mysql
    volumes:
      - ./app/src:/var/www/html
    networks:
      - lamp_network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=student_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lamp_network

volumes:
  mysql_data:

networks:
  lamp_network:
    driver: bridge

